### ISSUE TITLE
iconmelon.com dead

### ISSUE THREAD

**Issue by dandv** [legomushroom/iconmelon#13]
![image](https://cloud.githubusercontent.com/assets/33569/8327945/2bbafbc4-1a21-11e5-8ecc-bf47c42d4875.png)

**Comment by legomushroom** [comment]
@dandv thanks for the heads up!

**Comment by dandv** [comment]
Glad to see the page up! Maybe it's worth signing up for monitor2.com? It's free and checks if the site is up once a minute .UptimeRobot, once every 5.
