### ISSUE TITLE
Filtering does not work as expected

### ISSUE THREAD

**Issue by ErtugKaya** [legomushroom/iconmelon#6]
For instance filter for rocket and it gives you one icon. You need go through third page to see two more.

If that is intended, you should put a search box.

BTW, I think you need to drop pagination and show each icon set as loaded in the same page.

**Comment by legomushroom** [comment]
Hey, due to productivity concerns, we've made a pagination by 6 icon sets per page. Currently we're working on lazy load pagination, hope it will be implemented soon. Yes, it is working as 'filter' now. Thanks!

**Comment by dandv** [comment]
> due to productivity concerns

Is that because in Chrome, CPU usage is very high if many icons are loaded on the page?
